site_name: SeqLearner Documentation
nav:
    - Home: index.md
    - About: about.md
theme: readthedocs
repo_url: http://github.com/EliHei/SeqLearner
site_description: 'Documentation for SeqLearner, the multitask learning package for semi-supervised learning on biological sequences'